### ISSUE TITLE
Something went wrong with the Debug Trait

### ISSUE THREAD

**Issue by OvidiusCicero** [Ekleog/serde-error#1]
Relevant lines are

~~~
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.description)
    }
}

impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.description)
    }
}
~~~

so debug output is just the same as normal display.

not sure what the best solution would, probably to just `derive(Debug)` `serde_error::Error`

**Comment by Ekleog** [comment]
Is this actually a problem? To the best of my recollection, this behavior is also the one for eg. `anyhow::Error`

**Comment by OvidiusCicero** [comment]
Well, it's certainly subjective but I was very puzzled by not recognizing something printed as `serde_error`

**Comment by Ekleog** [comment]
Hmm… just to check: are you saying that [this](https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=8c4eb3ea76948f977198a9c77bbe1bdf) is unexpected behavior for you?

If so, then I think that anyhow is basically setting a standard in a way that serde-error probably should not override (unless it were to become much more popular than it currently is). If not, then I'm sorry but I'm not understanding the issue :sweat_smile:

**Comment by OvidiusCicero** [comment]
well, yes I'm used to that display and debug of error types print different stuff and that they look distinct like [that](https://play.integer32.com/?version=stable&mode=debug&edition=2018&gist=9b3b256c9ca39967e5b46bb8f32bacc6)

I also never used anyhow but if it set precedent it's better to follow that I gues

**Comment by Ekleog** [comment]
I'd suggest you try out anyhow, it's a great crate :) (or eyre, I've never tried it myself but heard it's just as good, though it appears to be less popular)
